-- Out-of-band policy broker: append-only intents/events/halts + mutable lease.
-- Additive only. Apply with the Supabase migration runner; never from the LLM.

create table if not exists public.broker_intents (
  id bigint generated by default as identity primary key,
  idempotency_key text not null unique,
  intent_type text not null check (intent_type in ('flip_lane', 'move_capital', 'rotate_secret')),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.broker_intent_events (
  id bigint generated by default as identity primary key,
  intent_id bigint not null references public.broker_intents(id),
  status text not null check (status in ('PENDING', 'EXECUTED', 'REJECTED', 'IN_DOUBT', 'HARD_STOP')),
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.broker_intent_attempts (
  id bigint generated by default as identity primary key,
  intent_id bigint not null unique references public.broker_intents(id),
  holder text not null check (length(trim(holder)) > 0),
  claimed_at timestamptz not null default now()
);

create table if not exists public.broker_halts (
  id bigint generated by default as identity primary key,
  scope text not null,
  action text not null check (action in ('halt', 'clear')),
  reason text,
  operator text,
  created_at timestamptz not null default now(),
  constraint broker_clear_requires_operator check (action <> 'clear' or length(trim(operator)) > 0)
);

create table if not exists public.broker_leases (
  name text primary key,
  holder text not null,
  expires_at timestamptz not null
);

create or replace function public.broker_block_append_only()
returns trigger language plpgsql as $$
begin
  raise exception '% is append-only', tg_table_name;
end;
$$;

drop trigger if exists broker_intents_append_only on public.broker_intents;
create trigger broker_intents_append_only before update or delete on public.broker_intents
for each row execute function public.broker_block_append_only();
drop trigger if exists broker_intent_events_append_only on public.broker_intent_events;
create trigger broker_intent_events_append_only before update or delete on public.broker_intent_events
for each row execute function public.broker_block_append_only();
drop trigger if exists broker_intent_attempts_append_only on public.broker_intent_attempts;
create trigger broker_intent_attempts_append_only before update or delete on public.broker_intent_attempts
for each row execute function public.broker_block_append_only();
drop trigger if exists broker_halts_append_only on public.broker_halts;
create trigger broker_halts_append_only before update or delete on public.broker_halts
for each row execute function public.broker_block_append_only();

drop trigger if exists broker_intents_no_truncate on public.broker_intents;
create trigger broker_intents_no_truncate before truncate on public.broker_intents
for each statement execute function public.broker_block_append_only();
drop trigger if exists broker_intent_events_no_truncate on public.broker_intent_events;
create trigger broker_intent_events_no_truncate before truncate on public.broker_intent_events
for each statement execute function public.broker_block_append_only();
drop trigger if exists broker_intent_attempts_no_truncate on public.broker_intent_attempts;
create trigger broker_intent_attempts_no_truncate before truncate on public.broker_intent_attempts
for each statement execute function public.broker_block_append_only();
drop trigger if exists broker_halts_no_truncate on public.broker_halts;
create trigger broker_halts_no_truncate before truncate on public.broker_halts
for each statement execute function public.broker_block_append_only();

create or replace function public.broker_block_terminal_event_override()
returns trigger language plpgsql as $$
declare latest_status text;
begin
  select status into latest_status from public.broker_intent_events
  where intent_id = new.intent_id order by id desc limit 1;
  if latest_status in ('EXECUTED', 'REJECTED', 'IN_DOUBT', 'HARD_STOP') then
    raise exception 'intent % is already terminal; outcomes are write-once', new.intent_id;
  end if;
  return new;
end;
$$;

drop trigger if exists broker_intent_events_terminal_write_once on public.broker_intent_events;
create trigger broker_intent_events_terminal_write_once
before insert on public.broker_intent_events
for each row execute function public.broker_block_terminal_event_override();

create or replace function public.broker_submit_intent(
  p_key text, p_type text, p_payload jsonb
) returns table(id bigint, created boolean)
language plpgsql security definer set search_path = public as $$
declare stored public.broker_intents%rowtype;
begin
  insert into public.broker_intents(idempotency_key, intent_type, payload)
  values (p_key, p_type, p_payload)
  on conflict (idempotency_key) do nothing
  returning broker_intents.* into stored;
  if found then
    return query select stored.id, true;
    return;
  end if;
  select * into stored from public.broker_intents where idempotency_key = p_key;
  if stored.intent_type <> p_type or stored.payload <> p_payload then
    raise exception 'idempotency_key reused for a different intent';
  end if;
  return query select stored.id, false;
end;
$$;

create or replace function public.broker_pending_intents(p_limit integer default 25)
returns table(id bigint, idempotency_key text, intent_type text, payload jsonb)
language plpgsql security definer set search_path = public as $$
begin
  if p_limit is null or p_limit <= 0 or p_limit > 100 then
    raise exception 'p_limit must be between 1 and 100';
  end if;
  return query
  select i.id, i.idempotency_key, i.intent_type, i.payload
  from public.broker_intents i
  left join lateral (
    select e.status from public.broker_intent_events e
    where e.intent_id = i.id order by e.id desc limit 1
  ) latest on true
  where coalesce(latest.status, 'PENDING') = 'PENDING'
  order by i.id asc limit p_limit;
end;
$$;

create or replace function public.broker_acquire_lease(
  p_name text, p_holder text, p_ttl_seconds double precision
) returns boolean language plpgsql security definer set search_path = public as $$
begin
  if p_ttl_seconds <= 0 or p_ttl_seconds::text in ('NaN', 'Infinity', '-Infinity') then
    return false;
  end if;
  insert into public.broker_leases(name, holder, expires_at)
  values (p_name, p_holder, clock_timestamp() + make_interval(secs => p_ttl_seconds))
  on conflict (name) do update set holder = excluded.holder, expires_at = excluded.expires_at
  where broker_leases.expires_at < clock_timestamp() or broker_leases.holder = excluded.holder;
  return exists(select 1 from public.broker_leases where name = p_name and holder = p_holder);
end;
$$;

create or replace function public.broker_claim_intent_attempt(
  p_intent_id bigint, p_holder text
) returns boolean language plpgsql security definer set search_path = public as $$
declare changed integer;
begin
  if p_holder is null or length(trim(p_holder)) = 0 then
    return false;
  end if;
  insert into public.broker_intent_attempts(intent_id, holder)
  values (p_intent_id, trim(p_holder))
  on conflict (intent_id) do nothing;
  get diagnostics changed = row_count;
  return changed = 1;
end;
$$;

create or replace function public.broker_renew_lease(
  p_name text, p_holder text, p_ttl_seconds double precision
) returns boolean language plpgsql security definer set search_path = public as $$
declare changed integer;
begin
  if p_ttl_seconds <= 0 or p_ttl_seconds::text in ('NaN', 'Infinity', '-Infinity') then
    return false;
  end if;
  update public.broker_leases
  set expires_at = clock_timestamp() + make_interval(secs => p_ttl_seconds)
  where name = p_name and holder = p_holder and expires_at >= clock_timestamp();
  get diagnostics changed = row_count;
  return changed = 1;
end;
$$;

create or replace function public.broker_release_lease(p_name text, p_holder text)
returns boolean language plpgsql security definer set search_path = public as $$
declare changed integer;
begin
  delete from public.broker_leases where name = p_name and holder = p_holder;
  get diagnostics changed = row_count;
  return changed = 1;
end;
$$;

alter table public.broker_intents enable row level security;
alter table public.broker_intent_events enable row level security;
alter table public.broker_intent_attempts enable row level security;
alter table public.broker_halts enable row level security;
alter table public.broker_leases enable row level security;
revoke all on public.broker_intents, public.broker_intent_events, public.broker_intent_attempts, public.broker_halts, public.broker_leases
from anon, authenticated;
grant select on public.broker_intents, public.broker_intent_attempts, public.broker_leases to service_role;
grant select, insert on public.broker_intent_events, public.broker_halts to service_role;
grant usage, select on sequence public.broker_intent_events_id_seq to service_role;
grant usage, select on sequence public.broker_halts_id_seq to service_role;
revoke all on function public.broker_submit_intent(text, text, jsonb) from public;
revoke all on function public.broker_pending_intents(integer) from public;
revoke all on function public.broker_claim_intent_attempt(bigint, text) from public;
revoke all on function public.broker_acquire_lease(text, text, double precision) from public;
revoke all on function public.broker_renew_lease(text, text, double precision) from public;
revoke all on function public.broker_release_lease(text, text) from public;
grant execute on function public.broker_submit_intent(text, text, jsonb) to service_role;
grant execute on function public.broker_pending_intents(integer) to service_role;
grant execute on function public.broker_claim_intent_attempt(bigint, text) to service_role;
grant execute on function public.broker_acquire_lease(text, text, double precision) to service_role;
grant execute on function public.broker_renew_lease(text, text, double precision) to service_role;
grant execute on function public.broker_release_lease(text, text) to service_role;
